import type { OrderRow } from "../src/lib/types";

export function orderFixture(overrides: Partial<OrderRow> = {}): OrderRow {
  const now = "2026-06-22T10:00:00.000Z";
  return {
    id: "order_1",
    public_id: "public_1",
    result_token_hash: "hash",
    email: "kapcsolat@example.com",
    name: "Teszt Elek",
    letter_type: "Panaszlevél",
    recipient: "Ügyfélszolgálat",
    problem_description: "A szolgáltatás nem a megbeszéltek szerint működött.",
    desired_result: "Kérem a hiba kijavítását.",
    tone: "Udvarias",
    previous_messages: null,
    selected_package: "basic",
    server_calculated_price: 890,
    currency: "huf",
    payment_status: "checkout_created",
    ai_status: "not_started",
    stripe_session_id: "cs_test_1",
    stripe_payment_intent_id: null,
    generated_letter: null,
    generation_count: 0,
    created_at: now,
    updated_at: now,
    paid_at: null,
    generated_at: null,
    error_message: null,
    subscription_id: null,
    billing_source: "checkout",
    letter_history: null,
    letter_email_sent: 0,
    checkout_idempotency_key: "84c31d7f-0c7c-4bf8-85e5-fcd6a0949681",
    checkout_input_hash: "input-hash",
    paid_amount: null,
    customer_email: "szamla@example.com",
    billing_buyer_type: "individual",
    billing_name: "Teszt Elek",
    billing_email: "szamla@example.com",
    billing_country: "HU",
    billing_postal_code: "1111",
    billing_city: "Budapest",
    billing_address_line1: "Példa utca 1.",
    billing_tax_number: null,
    invoice_status: "not_required",
    invoice_provider: null,
    invoice_number: null,
    invoice_external_id: null,
    invoice_pdf_url: null,
    szamlazz_invoice_id: null,
    szamlazz_invoice_number: null,
    invoice_sent_to_email: null,
    invoice_sent_at: null,
    invoice_created_at: null,
    invoice_email_status: "not_required",
    invoice_email_error_message: null,
    invoice_error_code: null,
    invoice_error_message: null,
    invoice_retry_count: 0,
    invoice_last_attempted_at: null,
    invoice_next_retry_at: null,
    invoiced_at: null,
    refund_invoice_status: "not_required",
    refund_amount: null,
    refund_stripe_id: null,
    letter_email_sent_versions: null,
    ...overrides,
  };
}
